version: 06-25-2019

plugins:
  - netlify-plugin-axe:
      axeFlags: '--rules color-contrast,html-has-lang'

build:
  lifecycle:
    init:
      - npm run foo
      - export VALUE=lol
      - echo "much wow"
    getCache:
      - echo 'curl custom cache'
    #install: npm install
    prebuild: echo "${secrets:privateKey}"
    build: |
      echo 'Hello Netlify Build!'
      npm run build
    # package:
    #   - zip -q -r .functions/package.zip src node_modules
