version: 06-25-2019

plugins:
  no-more-404:
    type: '@netlify/plugin-no-more-404'
    config:
      on404: 'error' # can switch to warn
      blankSlate: false # true to track diffs, false to clear cahce and start from scratch
  functions:
    type: '@netlify/plugin-functions'
    enabled: false
    config:
      functions:
        foo:
          handler: src/backend/whatever.js
          path: /api/lol
          method: POST
        bar:
          handler: src/backend/myFuncName.js
          path: /api/cool
          method: GET
  example:
    type: '@netlify/plugin-example'
    enabled: false
  cypress:
    type: '@netlify/plugin-cypress'
    config:
      baseUrl: ${env:URL, https://netlify.com}
      pageLoadTimeout: 60000
  notifier:
    type: '@netlify/plugin-notifier'
    enabled: false
    config:
      sms:
        provider: twilio
        TWILIO_ACCOUNT_SID: ${env:TWILIO_ACCOUNT_SID, 'NA'}
        TWILIO_AUTH_TOKEN: ${env:TWILIO_AUTH_TOKEN, 'NA'}
        TWILIO_PHONE_NUMBER: ${env:TWILIO_PHONE_NUMBER, 'NA'}
      notices:
        - event: postBuild
          type: email
          to: david@netlify.com
          subject: 'Your site is ready!'
          message: 'Horray!'
        - event: postBuild
          type: sms
          to: 727-687-1888
          message: 'Your build is published {url}!'
        - event: buildFailed
          type: webhook
          endpoint: 'https://my-webhook-endpoint.com/api'
          message: 'Your site build failed sorry charlie'
  lighthouse:
    type: '@netlify/plugin-lighthouse'
    enabled: ${env:LIGHTHOUSE_ENABLED, false}
    config:
      currentVersion: 0.0.4
      compareWithVersion: 0.0.3
  axe:
    type: '@netlify/plugin-axe'
    enabled: false
    config:
      axeFlags: '--rules color-contrast,html-has-lang' # https://github.com/dequelabs/axe-cli#running-specific-rules
  monorepo:
    type: '@netlify/plugin-monorepo'
    enabled: false
    config:
      files:
        - 'src/**'

build:
  functions: src/backend
  # command: echo 'hi'
  publish: build
  lifecycle:
    init:
      - npm run foo
      - export VALUE=lol
      - echo "much wow"
    getCache:
      - echo 'curl custom cache'
    #install: npm install
    # preBuild: echo "${secrets:privateKey}"
    build:
      - echo 'Hello Netlify Build!' && npm run build
    # package:
    #   - zip -q -r .functions/package.zip src node_modules
