version: 06-25-2019

plugins:
  # - netlify-plugin-functions:
  #     functions:
  #       foo:
  #         handler: src/foo.js
  #         path: /foo
  #         method: GET
  #       bar:
  #         handler: src/bar.js
  #         path: /bar
  #         method: GET
  - netlify-plugin-example:
      enabled: true
  - netlify-plugin-cypress:
      baseUrl: ${env:SITE, https://netlify.com}
      pageLoadTimeout: 60000
  - netlify-plugin-sitemap:
      baseUrl: ${env:SITE, https://netlify.com}
      distPath: build
      exclude: "**/dist"
  - netlify-plugin-notifier:
      # disabled b/c you need twilio keys for this to work
      enabled: false
      sms:
        provider: twilio
        TWILIO_ACCOUNT_SID: ${env:TWILIO_ACCOUNT_SID, 'NA'}
        TWILIO_AUTH_TOKEN: ${env:TWILIO_AUTH_TOKEN, 'NA'}
        TWILIO_PHONE_NUMBER: ${env:TWILIO_PHONE_NUMBER, 'NA'}
      notices:
        - event: postbuild
          type: email
          to: david@netlify.com
          subject: 'Your site is ready!'
          message: 'Horray!'
        - event: postbuild
          type: sms
          to: 727-687-1858
          message: 'Your build is published {url}!'
        - event: buildFailed
          type: webhook
          endpoint: 'https://my-webhook-endpoint.com/api'
          message: 'Your site build failed sorry charlie'
  - netlify-plugin-lighthouse:
      enabled: true
      currentVersion: 0.0.4
      compareWithVersion: 0.0.3
  - netlify-plugin-monorepo:
      enabled: false
      files:
        - "src/**"

build:
  functions: functions
  # command: echo 'hi'
  lifecycle:
    init:
      - npm run foo
      - export VALUE=lol
      - echo "much wow"
    getCache:
      - echo 'curl custom cache'
    #install: npm install
    prebuild: echo "${secrets:privateKey}"
    build: |
      echo 'Hello Netlify Build!'
      npm run build
    # package:
    #   - zip -q -r .functions/package.zip src node_modules
