build:
  publish: build
  functions: functions
  lifecycle:
    onInit: echo "Starting the build"
    onBuild: gulp build
    onEnd: echo "Ending the build"

plugins:
  # TODO: rename `type` to `package` next time `@netlify/build` is published
  # to npm
  - type: ./plugin
