# Build settings
build:
  functions: functions
  publish: build
  lifecycle:
    init:
      - npm run foo
      - echo "wow cool"
    getCache:
      - echo "neat-o"
    build:
      - echo 'Hello Netlify Build!' && npm run makeSite

# Build Plugins
plugins:
  - type: '@netlify/plugin-search-index'
  # - type: ./plugins/plugin-one
  # - type: ./plugins/plugin-two
  # - type: ./plugins/dynamic
  #   config:
  #     hook: init
  # - type: '@netlify/plugin-no-more-404'
  #   config:
  #     on404: 'error'
  #     blankSlate: false
  # - type: '@netlify/plugin-lighthouse'
  #   enabled: ${env:LIGHTHOUSE_ENABLED, false}
  #   config:
  #     currentVersion: 0.0.4
  #     compareWithVersion: 0.0.3
  # - type: '@netlify/plugin-axe'
  #   enabled: false
  #   config:
  #     # https://github.com/dequelabs/axe-cli#running-specific-rules
  #     axeFlags: '--rules color-contrast,html-has-lang'
