# Build Settings
build:
  functions: functions
  publish: build
  # Inline lifecycle hooks
  lifecycle:
    init:
      - echo "Starting the build"
    build:
      - npm run makeSite
    onEnd:
      - echo "Ending the build"

# Build plugins
plugins:
  - type: ./plugins/example
    config:
      hi: foo
