version: 06-25-2019

plugins:
  - ./plugins/netlify-plugin-cypress:
      baseUrl: "${env:SITE}"
      pageLoadTimeout: 60000
  - ./plugins/netlify-plugin-sitemap:
      exclude: "**/dist"
  - ./plugins/netlify-plugin-notify:
      emails:
        - david@netlify.com
        - jim@netlify.com
  # - netlify-cache-plugin:
  #     dir: 'lol-dir'
  #     ttl: 100000
  # - netlify-lighthouse-plugin: true

build:
  command: npm run build
  lifecycle:
    init:
      - npm run preBuildThing
      - export VALUE=lol
      - echo "much wow"
    getCache:
      - curl 'get custom cache thing'
    install: npm install && rm -rf badfile
    build:
      command: |
        echo 'Hello Netlify Build!'
        npm run build
    package:
      - zip -q -r .functions/package.zip src node_modules

addons:
