name: Build
on: [push]
env:
  CI: 'true'
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        node: [8.3.0, 13]
        exclude:
          - os: macOS-latest
            node: 8.3.0
          - os: windows-latest
            node: 8.3.0
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm install
      - name: Tests
        run: npm run test-ci
      - name: Coveralls test coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: 'true'
      ## Parallel test coverages do not currently work with Coveralls
      ## See https://github.com/coverallsapp/github-action/issues/13
      ## and https://github.com/coverallsapp/github-action/issues/18
      ## Which means only the fastest build (usually either Linux or Mac) is used.
      ## When this is fixed, the following lines should be commented out.
      # coverage:
      #   needs: build
      #   runs-on: ubuntu-latest
      #   steps:
      - name: Coveralls finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: 'true'
